services:
  juji-discord-bot:
    build: .
    restart: unless-stopped
    depends_on:
      - lavalink
      - redis
    env_file:
      - .env
    networks:
      - juji-network

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    networks:
      - juji-network

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx384m
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
    networks:
      - juji-network

networks:
  juji-network:
    external: true
