services:
  juji-discord-bot:
    image: ${IMAGE}
    restart: unless-stopped
    depends_on:
      - lavalink
      - redis
    env_file:
      - .env
    pull_policy: always
    networks:
      - juji-network

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    pull_policy: always
    networks:
      - juji-network

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    restart: unless-stopped
    pull_policy: always
    environment:
      - _JAVA_OPTIONS=-Xmx512m
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
    networks:
      - juji-network

networks:
  juji-network:
    external: true
